#! /bin/bash

ACTIVE_WIFI=$(nmcli con show --active | awk '/wifi/ { print $1 }')
if [[ -z "$ACTIVE_WIFI" ]]; then
	exit
else
	nmcli con show "$ACTIVE_WIFI" | awk '/802-11-wireless.ssid:/ { print $2 }'
fi

