#!/usr/bin/perl

# File generated by menutray v0.47

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/max/.config/menutray/schema.pl' instead!

use utf8;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('starred');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "pcmanfm &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $item->signal_connect('activate', sub {system "xterm &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "chromium &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Instant\ messaging");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-users",q{menu}));
    $item->signal_connect('activate', sub {system "pidgin &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Accessories");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("compton");
    $app->signal_connect('activate', sub {system "compton\ \-\-xrender\-sync\-fence &"});
    $app->set_property('tooltip_text', "Compositor\ for\ X11");
    $app->set_image('Gtk2::Image'->new_from_icon_name("compton",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system\ and\ manage\ the\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Galculator");
    $app->signal_connect('activate', sub {system "galculator &"});
    $app->set_property('tooltip_text', "Perform\ simple\ and\ scientific\ calculations");
    $app->set_image('Gtk2::Image'->new_from_icon_name("galculator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GPG\-Crypter");
    $app->signal_connect('activate', sub {system "gpg\-crypter &"});
    $app->set_property('tooltip_text', "GPG\-Crypter\ utility");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gpg\-crypter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ipython");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'ipython\' &"});
    $app->set_property('tooltip_text', "Enhanced\ interactive\ Python\ shell");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ipython",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Neovim\-Qt");
    $app->signal_connect('activate', sub {system "nvim\-qt\ \-\- &"});
    $app->set_property('tooltip_text', "Qt\ GUI\ for\ Neovim\ text\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("nvim\-qt",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Redshift");
    $app->signal_connect('activate', sub {system "redshift\-gtk &"});
    $app->set_property('tooltip_text', "Color\ temperature\ adjustment\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("redshift",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Winetricks");
    $app->signal_connect('activate', sub {system "winetricks\ \-\-gui &"});
    $app->set_property('tooltip_text', "Work\ around\ problems\ and\ install\ applications\ under\ Wine");
    $app->set_image('Gtk2::Image'->new_from_icon_name("winetricks",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xarchiver");
    $app->signal_connect('activate', sub {system "xarchiver &"});
    $app->set_property('tooltip_text', "A\ GTK\+\ only\ archive\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xarchiver",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xournal");
    $app->signal_connect('activate', sub {system "xournal &"});
    $app->set_property('tooltip_text', "Take\ handwritten\ notes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xournal",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Development");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Android\ Studio");
    $app->signal_connect('activate', sub {system "android\-studio &"});
    $app->set_property('tooltip_text', "The\ official\ Android\ IDE");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-studio",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Arduino\ IDE");
    $app->signal_connect('activate', sub {system "arduino &"});
    $app->set_property('tooltip_text', "Open\-source\ electronics\ prototyping\ platform");
    $app->set_image('Gtk2::Image'->new_from_icon_name("arduino",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Autodesk\ EAGLE");
    $app->signal_connect('activate', sub {system "eagle &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("eagle",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FLUID");
    $app->signal_connect('activate', sub {system "fluid &"});
    $app->set_property('tooltip_text', "FLTK\ GUI\ Designer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("fluid",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("IntelliJ\ IDEA\ Community\ Edition");
    $app->signal_connect('activate', sub {system "\"\/usr\/share\/intellijidea\-ce\/bin\/idea\.sh\" &"});
    $app->set_property('tooltip_text', "Develop\ with\ pleasure\!");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/intellijidea\-ce\/bin\/idea\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("IntelliJ\ IDEA\ Community\ Edition");
    $app->signal_connect('activate', sub {system "idea\.sh &"});
    $app->set_property('tooltip_text', "Develop\ with\ pleasure\!");
    $app->set_image('Gtk2::Image'->new_from_icon_name("idea",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ipython");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'ipython\' &"});
    $app->set_property('tooltip_text', "Enhanced\ interactive\ Python\ shell");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ipython",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Mission\ Control");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jmc &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Monitoring\ and\ Management\ Console");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jconsole &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ VisualVM");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jvisualvm &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Julia");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'julia\' &"});
    $app->set_property('tooltip_text', "High\-level\,\ high\-performance\ dynamic\ language\ for\ technical\ computing");
    $app->set_image('Gtk2::Image'->new_from_icon_name("julia",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("QStlink2");
    $app->signal_connect('activate', sub {system "qstlink2 &"});
    $app->set_property('tooltip_text', "A\ ST\-Link\ V2\ GUI");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qstlink2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Assistant");
    $app->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Designer");
    $app->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Linguist");
    $app->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("RStudio");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/rstudio\-bin &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("rstudio",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Education");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ Drum\ Grid");
    $app->signal_connect('activate', sub {system "drumstick\-drumgrid &"});
    $app->set_property('tooltip_text', "Drumstick\ Drum\ Grid");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ MIDI\ Player");
    $app->signal_connect('activate', sub {system "drumstick\-guiplayer &"});
    $app->set_property('tooltip_text', "Drumstick\ MIDI\ Player");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ Virtual\ Piano");
    $app->signal_connect('activate', sub {system "drumstick\-vpiano &"});
    $app->set_property('tooltip_text', "Drumstick\ Virtual\ Piano");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VMPK");
    $app->signal_connect('activate', sub {system "vmpk &"});
    $app->set_property('tooltip_text', "Virtual\ MIDI\ Piano\ Keyboard");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vmpk",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Games");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Dolphin\ Emulator");
    $app->signal_connect('activate', sub {system "dolphin\-emu &"});
    $app->set_property('tooltip_text', "A\ Wii\/GameCube\ Emulator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("dolphin\-emu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Dosbox");
    $app->signal_connect('activate', sub {system "dosbox &"});
    $app->set_property('tooltip_text', "Emulator\ with\ builtin\ DOS\ for\ running\ DOS\ Games");
    $app->set_image('Gtk2::Image'->new_from_icon_name("dosbox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Quadrapassel");
    $app->signal_connect('activate', sub {system "quadrapassel &"});
    $app->set_property('tooltip_text', "Fit\ falling\ blocks\ together");
    $app->set_image('Gtk2::Image'->new_from_icon_name("quadrapassel",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Graphics");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("CAVA\ visualizer");
    $app->signal_connect('activate', sub {system "cava &"});
    $app->set_property('tooltip_text', "Audio\ spectrum\ visualizer");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/cava\/icon\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("E\-book\ Viewer");
    $app->signal_connect('activate', sub {system "ebook\-viewer\ \-\-detach &"});
    $app->set_property('tooltip_text', "Viewer\ for\ E\-books\ in\ all\ the\ major\ formats");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calibre\-viewer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Gcolor2");
    $app->signal_connect('activate', sub {system "gcolor2 &"});
    $app->set_property('tooltip_text', "Choose\ colours\ from\ palette\ or\ screen");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/gcolor2\/icon\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.8 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LRF\ Viewer");
    $app->signal_connect('activate', sub {system "lrfviewer &"});
    $app->set_property('tooltip_text', "Viewer\ for\ LRF\ files\ \(SONY\ ebook\ format\ files\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calibre\-viewer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mirage");
    $app->signal_connect('activate', sub {system "mirage &"});
    $app->set_property('tooltip_text', "A\ fast\ GTK\+\ Image\ Viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mirage",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("XSane\ \-\ Scanning");
    $app->signal_connect('activate', sub {system "xsane &"});
    $app->set_property('tooltip_text', "Acquire\ images\ from\ a\ scanner");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xsane",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("yEd\ Graph\ Editor");
    $app->signal_connect('activate', sub {system "yed &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("yed",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("amsynth");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/amsynth &"});
    $app->set_property('tooltip_text', "Two\ oscillator\ subtractive\ software\ synthesizer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("amsynth",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Asunder\ CD\ Ripper");
    $app->signal_connect('activate', sub {system "asunder &"});
    $app->set_property('tooltip_text', "An\ application\ to\ save\ tracks\ from\ an\ Audio\ CD\ as\ WAV\,\ MP3\,\ OGG\,\ FLAC\,\ and\/or\ Wavpack\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("asunder",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Audacity");
    $app->signal_connect('activate', sub {system "env\ UBUNTU_MENUPROXY\=0\ audacity &"});
    $app->set_property('tooltip_text', "Record\ and\ edit\ audio\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("audacity",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("baudline");
    $app->signal_connect('activate', sub {system "baudline &"});
    $app->set_property('tooltip_text', "Time\-frequency\ browser\ designed\ for\ scientific\ visualization\ of\ the\ spectral\ domain\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("baudline",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("baudline_jack");
    $app->signal_connect('activate', sub {system "baudline_jack &"});
    $app->set_property('tooltip_text', "Time\-frequency\ browser\ designed\ for\ scientific\ visualization\ of\ the\ spectral\ domain\.\ With\ JACK\ suppport\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("baudline_jack",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Calf\ Plugin\ Pack\ for\ JACK");
    $app->signal_connect('activate', sub {system "calfjackhost &"});
    $app->set_property('tooltip_text', "Process\ and\ produce\ sounds\ using\ a\ set\ of\ plugins\ with\ JACK\ interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calf",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Carla");
    $app->signal_connect('activate', sub {system "carla &"});
    $app->set_property('tooltip_text', "Audio\ Plugin\ Host");
    $app->set_image('Gtk2::Image'->new_from_icon_name("carla",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Carla\ Control");
    $app->signal_connect('activate', sub {system "carla\-control &"});
    $app->set_property('tooltip_text', "Audio\ Plugin\ Host\ \(OSC\ Control\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("carla\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ Drum\ Grid");
    $app->signal_connect('activate', sub {system "drumstick\-drumgrid &"});
    $app->set_property('tooltip_text', "Drumstick\ Drum\ Grid");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ MIDI\ Player");
    $app->signal_connect('activate', sub {system "drumstick\-guiplayer &"});
    $app->set_property('tooltip_text', "Drumstick\ MIDI\ Player");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Drumstick\ Virtual\ Piano");
    $app->signal_connect('activate', sub {system "drumstick\-vpiano &"});
    $app->set_property('tooltip_text', "Drumstick\ Virtual\ Piano");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drumstick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FFADO\ Mixer");
    $app->signal_connect('activate', sub {system "ffado\-mixer &"});
    $app->set_property('tooltip_text', "Audio\ mixer\ for\ Firewire\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ffado",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Giada");
    $app->signal_connect('activate', sub {system "giada &"});
    $app->set_property('tooltip_text', "A\ looper\,\ drum\ machine\,\ sequencer\,\ live\ sampler\ and\ plugin\ host");
    $app->set_image('Gtk2::Image'->new_from_icon_name("giada",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HandBrake");
    $app->signal_connect('activate', sub {system "ghb &"});
    $app->set_property('tooltip_text', "Transcodes\ DVD\,\ Blu\-ray\,\ and\ other\ media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("hb\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HDSPConf");
    $app->signal_connect('activate', sub {system "hdspconf &"});
    $app->set_property('tooltip_text', "Hammerfall\ DSP\ control\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("hdspconf",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HDSPMixer");
    $app->signal_connect('activate', sub {system "hdspmixer &"});
    $app->set_property('tooltip_text', "Hammerfall\ DSP\ matrix\ mixer\ control\ GUI");
    $app->set_image('Gtk2::Image'->new_from_icon_name("hdspmixer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Hydrogen\ Drum\ Machine");
    $app->signal_connect('activate', sub {system "hydrogen &"});
    $app->set_property('tooltip_text', "Create\ drum\ sequences");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/hydrogen\/data\/img\/gray\/h2\-icon\.svg",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Kid3\-qt");
    $app->signal_connect('activate', sub {system "kid3\-qt &"});
    $app->set_property('tooltip_text', "Edit\ audio\ file\ metadata");
    $app->set_image('Gtk2::Image'->new_from_icon_name("kid3\-qt",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Lollypop");
    $app->signal_connect('activate', sub {system "lollypop &"});
    $app->set_property('tooltip_text', "Play\ and\ organize\ your\ music\ collection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.Lollypop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mixxx");
    $app->signal_connect('activate', sub {system "sh\ \-c\ \"pasuspender\ mixxx\ \|\|\ mixxx\" &"});
    $app->set_property('tooltip_text', "A\ digital\ DJ\ interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mixxx\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-player\-operation\-mode\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mpv",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MuseScore\ 2");
    $app->signal_connect('activate', sub {system "mscore &"});
    $app->set_property('tooltip_text', "Create\,\ play\ and\ print\ sheet\ music");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mscore",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("projectM\ PulseAudio\ Visualization");
    $app->signal_connect('activate', sub {system "projectM\-pulseaudio &"});
    $app->set_property('tooltip_text', "Visualization\ of\ PulseAudio\ streams\ with\ projectM");
    $app->set_image('Gtk2::Image'->new_from_icon_name("prjm16\-transparent",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ System\ Tray");
    $app->signal_connect('activate', sub {system "pasystray &"});
    $app->set_property('tooltip_text', "An\ Applet\ for\ PulseAudio");
    $app->set_image('Gtk2::Image'->new_from_icon_name("pasystray",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("QjackCtl");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/qjackctl &"});
    $app->set_property('tooltip_text', "QjackCtl\ is\ a\ JACK\ Audio\ Connection\ Kit\ Qt\ GUI\ Interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qjackctl",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qtractor");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/qtractor &"});
    $app->set_property('tooltip_text', "Qtractor\ is\ an\ Audio\/MIDI\ multi\-track\ sequencer\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qtractor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sonic\ Visualiser");
    $app->signal_connect('activate', sub {system "sonic\-visualiser &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sv\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Spotify");
    $app->signal_connect('activate', sub {system "spotify &"});
    $app->set_property('tooltip_text', "Spotify\ streaming\ music\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spotify\-client",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SuperCollider\ IDE");
    $app->signal_connect('activate', sub {system "scide &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sc_ide",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("synthv1");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/synthv1_jack &"});
    $app->set_property('tooltip_text', "synthv1\ is\ an\ old\ school\ polyphonic\ synthtesizer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("synthv1",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VMPK");
    $app->signal_connect('activate', sub {system "vmpk &"});
    $app->set_property('tooltip_text', "Virtual\ MIDI\ Piano\ Keyboard");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vmpk",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Network");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Connman\ UI\ Setup");
    $app->signal_connect('activate', sub {system "cmst &"});
    $app->set_property('tooltip_text', "QT\ GUI\ frontend\ for\ connman");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cmst",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firefox");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/firefox\/firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firefox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Inox");
    $app->signal_connect('activate', sub {system "inox &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("inox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Skype");
    $app->signal_connect('activate', sub {system "skype &"});
    $app->set_property('tooltip_text', "Skype\ Internet\ Telephony");
    $app->set_image('Gtk2::Image'->new_from_icon_name("skype",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("transmission",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("unison");
    $app->signal_connect('activate', sub {system "unison\-x11 &"});
    $app->set_property('tooltip_text', "File\ synchronisation\ tool\ for\ X11");
    $app->set_image('Gtk2::Image'->new_from_icon_name("unison",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Wireshark\ \(GTK\+\)");
    $app->signal_connect('activate', sub {system "wireshark\-gtk &"});
    $app->set_property('tooltip_text', "Network\ traffic\ analyzer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wireshark",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap");
    $app->signal_connect('activate', sub {system "zenmap &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap\ \(as\ root\)");
    $app->signal_connect('activate', sub {system "\/usr\/share\/zenmap\/su\-to\-zenmap\.sh &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Office");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Adobe\ Reader\ 9");
    $app->signal_connect('activate', sub {system "acroread &"});
    $app->set_property('tooltip_text', "Adobe\ PDF\ Viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("acroread",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Calibre");
    $app->signal_connect('activate', sub {system "calibre\ \-\-detach &"});
    $app->set_property('tooltip_text', "E\-book\ library\ management\:\ Convert\,\ view\,\ share\,\ catalogue\ all\ your\ e\-books");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calibre\-gui",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Edit\ E\-book");
    $app->signal_connect('activate', sub {system "ebook\-edit\ \-\-detach &"});
    $app->set_property('tooltip_text', "Edit\ e\-books\ in\ various\ formats");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calibre\-ebook\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\ by\ using\ Base\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zathura");
    $app->signal_connect('activate', sub {system "zathura &"});
    $app->set_property('tooltip_text', "A\ minimalistic\ document\ viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("zathura",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # OTHER # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Other");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-other",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("R");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'R\' &"});
    $app->set_property('tooltip_text', "language\ and\ environment\ for\ statistical\ computing\ and\ graphics");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/r\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("x\-sonicvisualiser");
    $app->signal_connect('activate', sub {system " &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sv\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("x\-sonicvisualiser\-layer");
    $app->signal_connect('activate', sub {system " &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sv\-icon",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Settings");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Adobe\ Flash\ Player");
    $app->signal_connect('activate', sub {system "flash\-player\-properties &"});
    $app->set_property('tooltip_text', "Preferences\ for\ Adobe\ Flash\ Player");
    $app->set_image('Gtk2::Image'->new_from_icon_name("flash\-player\-properties",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Connman\ UI\ Setup");
    $app->signal_connect('activate', sub {system "cmst &"});
    $app->set_property('tooltip_text', "QT\ GUI\ frontend\ for\ connman");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cmst",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Customize\ Look\ and\ Feel");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Desktop\ Preferences");
    $app->signal_connect('activate', sub {system "pcmanfm\ \-\-desktop\-pref &"});
    $app->set_property('tooltip_text', "Change\ desktop\ wallpapers\ and\ behavior\ of\ desktop\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("user\-desktop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/jre\/bin\/jcontrol &"});
    $app->set_property('tooltip_text', "Java\ Control\ Panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-jcontrol\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Policy\ Settings");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/jre\/bin\/policytool &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Keyboard\ and\ Mouse");
    $app->signal_connect('activate', sub {system "lxinput &"});
    $app->set_property('tooltip_text', "Configure\ keyboard\,\ mouse\,\ and\ other\ input\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("input\-keyboard",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Monitor\ Settings");
    $app->signal_connect('activate', sub {system "lxrandr &"});
    $app->set_property('tooltip_text', "Change\ screen\ resolution\ and\ configure\ external\ monitors");
    $app->set_image('Gtk2::Image'->new_from_icon_name("video\-display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Network\ Connections");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Popup\ Notifications");
    $app->signal_connect('activate', sub {system "mate\-notification\-properties &"});
    $app->set_property('tooltip_text', "Set\ your\ popup\ notification\ preferences");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mate\-notification\-properties",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app->signal_connect('activate', sub {system "libfm\-pref\-apps &"});
    $app->set_property('tooltip_text', "Select\ applications\ called\ on\ click\ on\ Web\ link\ or\ e\-mail\ address");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("printer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tint2\ Settings");
    $app->signal_connect('activate', sub {system "tint2conf &"});
    $app->set_property('tooltip_text', "Tool\ to\ configure\ the\ tint2\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tint2conf",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("System");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Configuration\ Editor");
    $app->signal_connect('activate', sub {system "gconf\-editor &"});
    $app->set_property('tooltip_text', "Directly\ edit\ your\ entire\ configuration\ database");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gconf\-editor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Connman\ UI\ Setup");
    $app->signal_connect('activate', sub {system "cmst &"});
    $app->set_property('tooltip_text', "QT\ GUI\ frontend\ for\ connman");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cmst",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Disk\ Usage\ Analyzer");
    $app->signal_connect('activate', sub {system "baobab &"});
    $app->set_property('tooltip_text', "Check\ folder\ sizes\ and\ available\ disk\ space");
    $app->set_image('Gtk2::Image'->new_from_icon_name("baobab",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system\ and\ manage\ the\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted_polkit &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gparted",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("gtk2fontsel");
    $app->signal_connect('activate', sub {system "gtk2fontsel &"});
    $app->set_property('tooltip_text', "Font\ selection\ and\ preview\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk2fontsel",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Hardware\ Locality\ lstopo");
    $app->signal_connect('activate', sub {system "lstopo &"});
    $app->set_property('tooltip_text', "Show\ hardware\ topology");
    $app->set_image('Gtk2::Image'->new_from_icon_name("lstopo",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Htop");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LSHW");
    $app->signal_connect('activate', sub {system "\/usr\/sbin\/gtk\-lshw &"});
    $app->set_property('tooltip_text', "HardWare\ LiSter");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/lshw\/artwork\/logo\.svg",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Manage\ Printing");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/xdg\-open\ http\:\/\/localhost\:631\/ &"});
    $app->set_property('tooltip_text', "CUPS\ Web\ Interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cups",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Oracle\ VM\ VirtualBox");
    $app->signal_connect('activate', sub {system "VirtualBox &"});
    $app->set_property('tooltip_text', "Run\ several\ virtual\ systems\ on\ a\ single\ host\ computer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("virtualbox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("printer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ranger");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("System\ Profiler\ and\ Benchmark");
    $app->signal_connect('activate', sub {system "hardinfo &"});
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/hardinfo\/pixmaps\/logo\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Task\ Manager");
    $app->signal_connect('activate', sub {system "lxtask &"});
    $app->set_property('tooltip_text', "Manage\ running\ processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Termite");
    $app->signal_connect('activate', sub {system "termite &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tint2");
    $app->signal_connect('activate', sub {system "tint2 &"});
    $app->set_property('tooltip_text', "Lightweight\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tint2",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Menutray");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Config");
    $app->signal_connect('activate', sub {system "\/home\/max\/bin\/neovim\-open\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Menu");
    $app->signal_connect('activate', sub {system "\/home\/max\/bin\/neovim\-open\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Schema");
    $app->signal_connect('activate', sub {system "\/home\/max\/bin\/neovim\-open\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/max\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
