
#! /bin/bash
#
# ~/.xsession
# sourced by display manager
# after system xinit scripts are sources

function set_xdg_vars {
	# taken from startlxqt
	export XDG_DATA_HOME="$HOME/.local/share"
	export XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"

	export XDG_CONFIG_HOME="$HOME/.config"
	export XDG_CONFIG_DIRS="/etc/xdg"

	export XDG_CACHE_HOME="$HOME/.cache"

	# Ensure the existance of the 'Desktop' folder
	if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
		. "$XDG_CONFIG_HOME/user-dirs.dirs"
		export XDG_{DESKTOP,DOWNLOAD,TEMPLATES,PUBLICSHARE,DOCUMENTS,MUSIC,PICTURES,VIDEOS}_DIR
	else
		export XDG_DESKTOP_DIR="$HOME/Desktop"
	fi
	mkdir -p "$XDG_DESKTOP_DIR"

	export XDG_CURRENT_DESKTOP=i3

	# get all of this environment into systemd
	systemctl --user import-environment XDG_{DATA,CONFIG,CACHE}_{HOME,DIRS}
	systemctl --user import-environment XDG_{DESKTOP,DOWNLOAD,TEMPLATES,PUBLICSHARE,DOCUMENTS,MUSIC,PICTURES,VIDEOS}_DIR
}

set_xdg_vars

#
# X session preferences
#

xset r rate 275 25
configure_monitors

GLOBAL_PROFILE=/etc/profile
ENV_FILE="$HOME"/.env
STARTUP_FILE="$HOME"/.startup

# get normal environment into systemd user session
[[ -f /etc/profile ]] && . /etc/profile
[[ -f "$ENV_FILE" ]] && . "$ENV_FILE"

systemctl --user import-environment PATH EDITOR PAGER BROWSER SUDO_EDITOR XDG_SESSION_PATH XDG_SEAT
# activates x11 detection and run a window manager if necessary
systemctl --user start managed-xorg.path dummy-desktop.path

# pulseaudio bell
#pacmd load-sample bell-440 /home/max/.config/systemd/data/bell-440.wav
#pacmd load-module module-x11-bell display=:0 sample=bell-440

if [[ -f "$STARTUP_FILE" ]]; then
	while read -r desktop_file; do
		# skip 'commented' lines
		[[ $desktop_file = \#* ]] && continue
		# else
		dex -v $desktop_file
	done < "$STARTUP_FILE"
fi


# vim : ft=sh
