
#! /bin/bash
#
# ~/.xsession
# sourced by display manager
# after system xinit scripts are sourced

function set_xdg_vars {
	XDG_DATA_HOME="$HOME/.local/share"
	XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"
	XDG_CONFIG_HOME="$HOME/.config"
	XDG_CONFIG_DIRS="/etc/xdg"
	XDG_CACHE_HOME="$HOME/.cache"
	export XDG_CURRENT_DESKTOP="i3"

	export XDG_DATA_HOME
	export XDG_DATA_DIRS
	export XDG_CONFIG_HOME
	export XDG_CONFIG_DIRS
	export XDG_CACHE_HOME
	export XDG_CURRENT_DESKTOP

	# Ensure the existance of the 'Desktop' folder
	if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
		. "$XDG_CONFIG_HOME/user-dirs.dirs"
		export XDG_DESKTOP_DIR
		export XDG_DOWNLOAD_DIR
		export XDG_TEMPLATES_DIR
		export XDG_PUBLICSHARE_DIR
		export XDG_DOCUMENTS_DIR
		export XDG_MUSIC_DIR
		export XDG_PICTURES_DIR
		export XDG_VIDEOS_DIR
	else
		XDG_DESKTOP_DIR="$HOME/Desktop"
		export XDG_DESKTOP_DIR
	fi
	mkdir -p "$XDG_DESKTOP_DIR"

	# get all of this environment into systemd
	for envvar in DATA_HOME DATA_DIRS CONFIG_HOME CONFIG_DIRS CACHE_HOME CURRENT_DESKTOP; do
		systemctl --user import-environment XDG_${envvar}
	done

	for envvar in DESKTOP DOWNLOAD TEMPLATES PUBLICSHARE DOCUMENTS MUSIC PICTURES VIDEOS; do
		systemctl --user import-environment XDG_${envvar}_DIR
	done
}

set_xdg_vars

#
# X session preferences
#

GLOBAL_PROFILE=/etc/profile
ENV_FILE="$HOME"/.env

# get normal environment into systemd user session
# import all system variables and some user variables
[[ -f /etc/profile ]] && . /etc/profile
systemctl --user import-environment

[[ -f "$ENV_FILE" ]] && . "$ENV_FILE"
systemctl --user import-environment PATH EDITOR PAGER BROWSER SUDO_EDITOR XDG_SESSION_PATH XDG_SEAT

systemctl --user start desktop.target

# pulseaudio bell
#pacmd load-sample bell-440 /home/max/.config/systemd/data/bell-440.wav
#pacmd load-module module-x11-bell display=:0 sample=bell-440

# vim : ft=sh
