# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/bin:$PATH
export PATH

# start X automatically, without login manager
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	bash ~/bin/confirm_startx && exec startx
fi
